export const enum ElementTypeEnum {
  Background = 'background',
  IconGroup = 'icon-group',
  Title = 'title',
  Desc = 'desc',
  ItemsGroup = 'items-group',
  ItemIconGroup = 'item-icon-group',
  ItemIcon = 'item-icon',
  ItemLabel = 'item-label',
  ItemDesc = 'item-desc',
  ItemValue = 'item-value',
  ItemsIllus = 'items-illus',
  BtnAdd = 'btn-add',
  BtnRemove = 'btn-remove',
  IllusGroup = 'illus-group',
  IllusVolume = 'illus-volume',
  Illus = 'illus',
  BtnsGroup = 'btns-group',

  Unknown = 'unknown',
}
